---
# Copyright The Enterprise Contract Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: push-bundles

on:
  push:
    branches:
    - main
    paths:
    - policy/**
    - data/**

  workflow_dispatch:

permissions:
  contents: read

jobs:
  push-policy-bundles:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        # So we can see in which commit a bundle's content was
        # most recently updated
        fetch-depth: 0

    - name: Setup Go environment
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: go.mod
        cache: true

    - name: Docker login (quay.io/enterprise-contract)
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      with:
        # See also BUNDLE_REPO defined in Makefile
        registry: quay.io
        username: ${{ secrets.BUNDLE_PUSH_USER_EC }}
        password: ${{ secrets.BUNDLE_PUSH_PASS_EC }}

    - name: Push bundles (quay.io/enterprise-contract)
      env:
        EC_AUTOMATION_KEY: ${{ secrets.EC_AUTOMATION_KEY }}
        APP_INSTALL_ID: 32872589
      run: hack/update-bundles.sh
