---
name: push-bundles

on:
  push:
    branches:
    - main
    paths:
    - policy/**
    - data/**

  workflow_dispatch:

permissions:
  contents: read

jobs:
  push-policy-bundles:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        # So we can see in which commit a bundle's content was
        # most recently updated
        fetch-depth: 0

    - name: Setup Go environment
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: go.mod
        cache: true

    # TODO: Remove this once all references to quay.io/hacbs-contract are removed
    - name: Docker login
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        # See also BUNDLE_REPO defined in Makefile
        registry: quay.io
        username: ${{ secrets.BUNDLE_PUSH_USER }}
        password: ${{ secrets.BUNDLE_PUSH_PASS }}

    # TODO: Remove this once all referecnes to quay.io/hacbs-contract are removed
    - name: Push bundles
      env:
        EC_AUTOMATION_KEY: ${{ secrets.EC_AUTOMATION_KEY }}
        APP_INSTALL_ID: 32872589
        REPO_PREFIX: quay.io/hacbs-contract/
      run: hack/update-bundles.sh

    - name: Docker login (quay.io/enterprise-contract)
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        # See also BUNDLE_REPO defined in Makefile
        registry: quay.io
        username: ${{ secrets.BUNDLE_PUSH_USER_EC }}
        password: ${{ secrets.BUNDLE_PUSH_PASS_EC }}

    - name: Push bundles (quay.io/enterprise-contract)
      env:
        EC_AUTOMATION_KEY: ${{ secrets.EC_AUTOMATION_KEY }}
        APP_INSTALL_ID: 32872589
      run: hack/update-bundles.sh

