---
name: npm-publish-antora-extension

"on":
  push:
    branches:
    - main
    paths:
    - 'antora/ec-policies-antora-extension/**'

permissions:
  contents: read

jobs:
  release-antora-extension:
    name: Release to NPM
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

    - name: Setup node
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        cache: 'npm'
        cache-dependency-path: 'antora/ec-policies-antora-extension/package-lock.json'
        node-version-file: 'antora/ec-policies-antora-extension/package.json'

    - name: Publish npm package
      run: make npm-publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
