---
name: npm-publish-antora-extension

"on":
  push:
    branches:
    - main
    paths:
    - 'antora/ec-policies-antora-extension/**'

permissions:
  contents: read

jobs:
  release-antora-extension:
    name: Release to NPM
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout code
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

    - name: Setup node
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        cache: 'npm'
        cache-dependency-path: 'antora/ec-policies-antora-extension/package-lock.json'
        node-version-file: 'antora/ec-policies-antora-extension/package.json'

    - name: Publish npm package
      run: make npm-publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
